# 本文件将对故障树标准文件的编写进行说明示范。

# 标准文件采用toml格式进行编写。编码为UTF-8。

# 首先文件名需要包含三个基本信息：版本号_部件名_故障树名称。
# 其中，部件名只能从下列五种中文名中选择：主轴承、齿轮箱、塔架、叶片、机舱、发电机。并请文件创建在./faulttree文件夹下对应的部件文件夹中。
# 进行故障树判断时，将根据数据对应测点所在的部位调用相关故障树文件进行判断。
# eg：1.1_主轴承_BearingInnerLoopFailure，放置于路径"./faulttree/主轴承"中
# eg：1.1_齿轮箱_GearBreakage，放置于路径"./faulttree/齿轮箱"中

